### PR TITLE
Basic app with node, express, and mongodb

### PR DESCRIPTION
**Pull request by nickn10**
https://evening-inlet-63684.herokuapp.com/

### CODE REVIEW

**Comment by SamirJouni** [comment]
The code you pushed has conflicts that are to complex to be fixed in the web editor.

**Comment by SamirJouni** [comment]
conflicts

Dude, I appreciate your efforts but there are two things going wrong here.
First of all, please don't make pull requests directly to the master branch. Instead, create your own branch in your fork, push to it, and make a pull request to it in the original repo. :)
This way I would be able to merge it with master, hopefully ! :)

**Comment by SamirJouni** [comment]
Also another tip for you:
You made massive changes before making the pull request. This is really bad, because it usually creates such conflicts and makes it very difficult to resolve them. 
I mean you added/deleted this many lines respectively: +1,727/−143 
If you are working for a company and you do this, they will be really pissed ! XD
I hope that you learned something new today. :)

**Comment by nickn10** [comment]
I apologize for the mess, this is all still very new to me. Can this pull request be removed/ deleted?

**Comment by SamirJouni** [comment]
Dude, no need to apologize ! LOL
This wasn't the point of what I said... XD
The point was to show you a better way of doing things bro ! We are all new here. I too started from nothing. :)
You can close the pull request (which you already did) and make a new one. Push to a branch on your fork then make a pull request from it ! I'm very interested to see your code in action ! :)

**Pull request closed without merging**
