### PR TITLE
Modify MongoDb URL

### PR DESCRIPTION
**Pull request by V6g1**
Existing code for signup works fine but using "MongoDB compass connection URL" requires an environmental set to start the Mongo Server in local machine that cause confusion for user ,  I inserted an alternative as MongoDb Atlas URL sample for use free existing Atlas cloud which Auto configures the environment ,also allows the devs to run the project with less effort .

Project used ES6 Import feature that required the "type":"common.js" which is missing, i added it in package.json file the bug in as fixed .

### CODE REVIEW

**Comment by l-white** [comment]
@MattCSmith Is it okay with you if we merge these changes? I'm not familiar with MongoDB

**Comment by V6g1** [comment]
Yeah it will work fine. I included the alternative way as comment in code

**Comment by V6g1** [comment]
Command*

**Comment by l-white** [comment]
@V6g1 I spoke to Andrei about this and it was decided to keep the repo as simple as possible without a lot of additional functionality because there are many beginners who contribute to it, so we aren't going to be incorporating Mongo DB at this time.

**Pull request closed without merging**
